### ISSUE TITLE
Reply 

### ISSUE THREAD

**Issue by jkariscodes** [gthaka/next-botted#79]
The user input message seems to have an issue with the placeholder image display as shown below.
![image](https://github.com/gthaka/next-botted/assets/23359514/10667c2d-08a9-4f09-a2fb-49d7344ce239)

**Comment by gthaka** [comment]
Just seen the service provider stopped serving Images, hence the error

![image](https://github.com/gthaka/next-botted/assets/6692971/192d96fb-0a7d-4085-af6c-53c6c630af04)

will replace it with another service
